// Code generated by entc, DO NOT EDIT.

package ent

import (
	"simple-bank/ent/account"
	"simple-bank/ent/entry"
	"simple-bank/ent/schema"
	"simple-bank/ent/transfer"
	"time"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	accountMixin := schema.Account{}.Mixin()
	accountMixinFields0 := accountMixin[0].Fields()
	_ = accountMixinFields0
	accountMixinFields1 := accountMixin[1].Fields()
	_ = accountMixinFields1
	accountFields := schema.Account{}.Fields()
	_ = accountFields
	// accountDescCreateTime is the schema descriptor for create_time field.
	accountDescCreateTime := accountMixinFields1[0].Descriptor()
	// account.DefaultCreateTime holds the default value on creation for the create_time field.
	account.DefaultCreateTime = accountDescCreateTime.Default.(func() time.Time)
	// accountDescUpdateTime is the schema descriptor for update_time field.
	accountDescUpdateTime := accountMixinFields1[1].Descriptor()
	// account.DefaultUpdateTime holds the default value on creation for the update_time field.
	account.DefaultUpdateTime = accountDescUpdateTime.Default.(func() time.Time)
	// account.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	account.UpdateDefaultUpdateTime = accountDescUpdateTime.UpdateDefault.(func() time.Time)
	// accountDescOwner is the schema descriptor for owner field.
	accountDescOwner := accountFields[0].Descriptor()
	// account.OwnerValidator is a validator for the "owner" field. It is called by the builders before save.
	account.OwnerValidator = func() func(string) error {
		validators := accountDescOwner.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
			validators[2].(func(string) error),
		}
		return func(owner string) error {
			for _, fn := range fns {
				if err := fn(owner); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// accountDescBalance is the schema descriptor for balance field.
	accountDescBalance := accountFields[1].Descriptor()
	// account.DefaultBalance holds the default value on creation for the balance field.
	account.DefaultBalance = accountDescBalance.Default.(int32)
	// accountDescCurrency is the schema descriptor for currency field.
	accountDescCurrency := accountFields[2].Descriptor()
	// account.CurrencyValidator is a validator for the "currency" field. It is called by the builders before save.
	account.CurrencyValidator = accountDescCurrency.Validators[0].(func(string) error)
	// accountDescID is the schema descriptor for id field.
	accountDescID := accountMixinFields0[0].Descriptor()
	// account.DefaultID holds the default value on creation for the id field.
	account.DefaultID = accountDescID.Default.(func() uuid.UUID)
	entryMixin := schema.Entry{}.Mixin()
	entryMixinFields0 := entryMixin[0].Fields()
	_ = entryMixinFields0
	entryMixinFields1 := entryMixin[1].Fields()
	_ = entryMixinFields1
	entryFields := schema.Entry{}.Fields()
	_ = entryFields
	// entryDescCreateTime is the schema descriptor for create_time field.
	entryDescCreateTime := entryMixinFields1[0].Descriptor()
	// entry.DefaultCreateTime holds the default value on creation for the create_time field.
	entry.DefaultCreateTime = entryDescCreateTime.Default.(func() time.Time)
	// entryDescUpdateTime is the schema descriptor for update_time field.
	entryDescUpdateTime := entryMixinFields1[1].Descriptor()
	// entry.DefaultUpdateTime holds the default value on creation for the update_time field.
	entry.DefaultUpdateTime = entryDescUpdateTime.Default.(func() time.Time)
	// entry.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	entry.UpdateDefaultUpdateTime = entryDescUpdateTime.UpdateDefault.(func() time.Time)
	// entryDescID is the schema descriptor for id field.
	entryDescID := entryMixinFields0[0].Descriptor()
	// entry.DefaultID holds the default value on creation for the id field.
	entry.DefaultID = entryDescID.Default.(func() uuid.UUID)
	transferMixin := schema.Transfer{}.Mixin()
	transferMixinFields0 := transferMixin[0].Fields()
	_ = transferMixinFields0
	transferMixinFields1 := transferMixin[1].Fields()
	_ = transferMixinFields1
	transferFields := schema.Transfer{}.Fields()
	_ = transferFields
	// transferDescCreateTime is the schema descriptor for create_time field.
	transferDescCreateTime := transferMixinFields1[0].Descriptor()
	// transfer.DefaultCreateTime holds the default value on creation for the create_time field.
	transfer.DefaultCreateTime = transferDescCreateTime.Default.(func() time.Time)
	// transferDescUpdateTime is the schema descriptor for update_time field.
	transferDescUpdateTime := transferMixinFields1[1].Descriptor()
	// transfer.DefaultUpdateTime holds the default value on creation for the update_time field.
	transfer.DefaultUpdateTime = transferDescUpdateTime.Default.(func() time.Time)
	// transfer.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	transfer.UpdateDefaultUpdateTime = transferDescUpdateTime.UpdateDefault.(func() time.Time)
	// transferDescID is the schema descriptor for id field.
	transferDescID := transferMixinFields0[0].Descriptor()
	// transfer.DefaultID holds the default value on creation for the id field.
	transfer.DefaultID = transferDescID.Default.(func() uuid.UUID)
}
