// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Account is the predicate function for account builders.
type Account func(*sql.Selector)

// Entry is the predicate function for entry builders.
type Entry func(*sql.Selector)

// Transfer is the predicate function for transfer builders.
type Transfer func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
